using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.HighDefinition;
using Debug = UnityEngine.Debug;
using Object = UnityEngine.Object;

namespace AmirTemur.Editor
{
    /// <summary>
    /// Stage 1 of BuildAll: importer settings, MaterialLibrary rebuild, HDRP/Lit materials for the Poly Haven models
    /// (with generated mask / base-colour-alpha textures where process_assets.py could not produce them), importer material remaps,
    /// prop prefabs under Assets/AmirTemur/Art/Prefabs/&lt;key&gt;.prefab and the city.json copy.
    /// </summary>
    public static class AssetImportSetup
    {
        public const string ModelsFolder = "Assets/AmirTemur/Art/Models";
        public const string ArtFolder = "Assets/AmirTemur/Art";
        public const string ModelMaterialsFolder = "Assets/AmirTemur/Art/Materials/Models";
        public const string DataFolder = "Assets/AmirTemur/Data";
        public const string CityJsonSource = "D:/Tashkent city/data/city.json";
        public const int LodGroupTriangleThreshold = 50000;
        public const float LodCullScreenHeight = 0.02f;

        /// <summary>Real-world size the prefab should have. The measured extent (height, or footprint for 'horizontal') is compared
        /// against it and a corrective uniform scale is applied only when the ratio is outside [1/ScaleTolerance, ScaleTolerance].</summary>
        class Target
        {
            public float size = 1f;
            public bool horizontal;
            public string[] keepChildren;   // explicit variant selection (substring match on direct children)
            public string preferChild;      // cluster containing this child wins when several variants are packed side by side
        }

        const float ScaleTolerance = 1.5f;

        static readonly Dictionary<string, Target> Targets = new()
        {
            ["tree_jacaranda"] = new Target { size = 12f },     // file: ~19 m -> scaled to 12 m
            ["tree_small"] = new Target { size = 5f },          // file: ~4.5 m
            ["tree_island"] = new Target { size = 6f },         // file: ~3.4 m -> scaled up
            ["shrub_02"] = new Target { size = 1.3f },
            ["shrub_03"] = new Target { size = 0.45f },
            ["shrub_04"] = new Target { size = 0.3f },
            ["fir_sapling"] = new Target { size = 7f },         // file: ~8.7 m (kept)
            ["lamp_01"] = new Target { size = 4.5f },
            ["lamp_02"] = new Target { size = 4.5f },
            ["bench_wood"] = new Target { size = 0.9f },
            ["bench_modern"] = new Target { size = 0.5f, keepChildren = new[] { "seat_bench", "suspended_support_02" } },
            ["trash_can"] = new Target { size = 0.9f },
            ["hydrant"] = new Target { size = 0.8f },
            ["manhole"] = new Target { size = 0.7f, horizontal = true },
            ["horse_statue"] = new Target { size = 2.5f },      // file: 22 cm figurine -> ~11x
            ["planter"] = new Target { size = 0.45f },
            ["car_covered"] = new Target { size = 1.45f },
        };

        const StaticEditorFlags PropStaticFlags = StaticEditorFlags.BatchingStatic | StaticEditorFlags.OccludeeStatic
            | StaticEditorFlags.ReflectionProbeStatic | StaticEditorFlags.ContributeGI;

        // <prefix>_<kind>_<res>.<ext> as produced by Poly Haven (copied verbatim by process_assets.py)
        static readonly Regex RawRx = new(@"^(?<prefix>.+?)_(?<kind>diff|diffuse|nor_gl|nor_dx|arm|rough|ao|metal|alpha|mask|disp|opacity|spec)_(?<res>\d+k)\.(?<ext>png|jpg|jpeg|exr|tga)$", RegexOptions.IgnoreCase);
        // generated by process_assets.py (or by this class)
        static readonly Regex GenRx = new(@"^(?<prefix>.+)_(?<kind>Mask|BaseColorA)\.png$", RegexOptions.IgnoreCase);

        class TexGroup
        {
            public string prefix, dir;
            public string diff, nor, norDx, arm, rough, ao, metal, alpha, rawMask, disp, opacity;
            public string mask, baseA; // generated
            public string AlphaSource => alpha ?? opacity ?? rawMask;
        }

        [MenuItem("AmirTemur/Asset Import Setup")]
        public static void Run()
        {
            var sw = Stopwatch.StartNew();
            var log = new StringBuilder();
            log.AppendLine("[AssetImportSetup] start");

            AssetDatabase.Refresh();

            int reimported = EnsureImportSettings(log);
            log.AppendLine($"[AssetImportSetup] importer settings re-checked, {reimported} asset(s) reimported");

            MaterialLibrary.RebuildAll();
            log.AppendLine($"[AssetImportSetup] MaterialLibrary rebuilt ({MaterialLibrary.Definitions.Count} definitions)");

            int materials = 0, prefabs = 0;
            var missing = new List<string>();
            foreach (var kv in PrefabLibrary.Sources)
            {
                string key = kv.Key, model = kv.Value;
                string fbx = $"{ModelsFolder}/{model}/{model}.fbx";
                if (AssetDatabase.LoadAssetAtPath<GameObject>(fbx) == null)
                {
                    missing.Add($"{key} ({fbx})");
                    continue;
                }
                try { materials += BuildModelMaterials(model, fbx, log); }
                catch (Exception e) { Debug.LogError($"[AssetImportSetup] materials for {model} failed: {e}"); }
                try { if (BuildPrefab(key, model, fbx, log)) prefabs++; }
                catch (Exception e) { Debug.LogError($"[AssetImportSetup] prefab for {key} failed: {e}"); }
            }

            CopyCityJson(log);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            log.AppendLine($"[AssetImportSetup] done in {sw.Elapsed.TotalSeconds:F1}s: {materials} model materials, {prefabs}/{PrefabLibrary.Sources.Count} prefabs" +
                           (missing.Count > 0 ? $", missing models: {string.Join(", ", missing)}" : ""));
            Debug.Log(log.ToString());
        }

        // ------------------------------------------------------------------ importer settings

        /// <summary>Re-applies TextureImportPostprocessor rules to assets already imported before the postprocessor existed.</summary>
        static int EnsureImportSettings(StringBuilder log)
        {
            int count = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:Texture", new[] { ArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!TextureImportPostprocessor.Owns(path)) continue;
                if (AssetImporter.GetAtPath(path) is not TextureImporter ti) continue;
                if (TextureImportPostprocessor.ApplyTexture(ti, path)) { ti.SaveAndReimport(); count++; }
            }
            foreach (string guid in AssetDatabase.FindAssets("t:GameObject", new[] { ModelsFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!TextureImportPostprocessor.IsModelPath(path)) continue;
                if (AssetImporter.GetAtPath(path) is not ModelImporter mi) continue;
                if (TextureImportPostprocessor.ApplyModel(mi, path)) { mi.SaveAndReimport(); count++; log.AppendLine($"  model importer updated: {path}"); }
            }
            return count;
        }

        // ------------------------------------------------------------------ textures per model

        static Dictionary<string, TexGroup> CollectTextureGroups(string texDir)
        {
            var groups = new Dictionary<string, TexGroup>(StringComparer.OrdinalIgnoreCase);
            string full = Path.Combine(Directory.GetCurrentDirectory(), texDir);
            if (!Directory.Exists(full)) return groups;

            TexGroup Get(string prefix)
            {
                if (!groups.TryGetValue(prefix, out var g)) { g = new TexGroup { prefix = prefix, dir = texDir }; groups[prefix] = g; }
                return g;
            }

            foreach (string file in Directory.GetFiles(full))
            {
                string name = Path.GetFileName(file);
                if (name.EndsWith(".meta", StringComparison.OrdinalIgnoreCase)) continue;
                string assetPath = $"{texDir}/{name}";

                var gm = GenRx.Match(name);
                if (gm.Success)
                {
                    var g = Get(gm.Groups["prefix"].Value);
                    if (gm.Groups["kind"].Value.Equals("Mask", StringComparison.OrdinalIgnoreCase)) g.mask = assetPath; else g.baseA = assetPath;
                    continue;
                }
                var m = RawRx.Match(name);
                if (!m.Success) continue;
                var grp = Get(m.Groups["prefix"].Value);
                switch (m.Groups["kind"].Value.ToLowerInvariant())
                {
                    case "diff": case "diffuse": grp.diff ??= assetPath; break;
                    case "nor_gl": grp.nor ??= assetPath; break;
                    case "nor_dx": grp.norDx ??= assetPath; break;
                    case "arm": grp.arm ??= assetPath; break;
                    case "rough": grp.rough ??= assetPath; break;
                    case "ao": grp.ao ??= assetPath; break;
                    case "metal": grp.metal ??= assetPath; break;
                    case "alpha": grp.alpha ??= assetPath; break;
                    case "mask": grp.rawMask ??= assetPath; break;
                    case "disp": grp.disp ??= assetPath; break;
                    case "opacity": grp.opacity ??= assetPath; break;
                }
            }
            return groups;
        }

        /// <summary>process_assets.py fails on EXR sources (PIL); build the missing HDRP mask / alpha base colour on the GPU here.</summary>
        static void EnsureGeneratedTextures(TexGroup g, StringBuilder log)
        {
            if (g.mask == null && (g.rough != null || g.arm != null))
            {
                string outPath = $"{g.dir}/{g.prefix}_Mask.png";
                try { if (GenerateMask(g, outPath)) { g.mask = outPath; log.AppendLine($"  generated {outPath}"); } }
                catch (Exception e) { Debug.LogWarning($"[AssetImportSetup] mask generation failed for {g.prefix}: {e.Message}"); }
            }
            if (g.baseA == null && g.diff != null && g.AlphaSource != null)
            {
                string outPath = $"{g.dir}/{g.prefix}_BaseColorA.png";
                try { if (GenerateBaseColorA(g.diff, g.AlphaSource, outPath)) { g.baseA = outPath; log.AppendLine($"  generated {outPath}"); } }
                catch (Exception e) { Debug.LogWarning($"[AssetImportSetup] base colour alpha generation failed for {g.prefix}: {e.Message}"); }
            }
        }

        static Texture2D Load(string path) => string.IsNullOrEmpty(path) ? null : AssetDatabase.LoadAssetAtPath<Texture2D>(path);

        /// <summary>GPU read-back of any imported texture (works without Read/Write enabled). sRGB=true keeps sRGB-encoded bytes.</summary>
        static Color32[] ReadPixels(Texture2D src, int w, int h, bool srgb)
        {
            var rt = RenderTexture.GetTemporary(w, h, 0, RenderTextureFormat.ARGB32, srgb ? RenderTextureReadWrite.sRGB : RenderTextureReadWrite.Linear);
            var prev = RenderTexture.active;
            Texture2D tmp = null;
            try
            {
                Graphics.Blit(src, rt);
                RenderTexture.active = rt;
                tmp = new Texture2D(w, h, TextureFormat.RGBA32, false, !srgb);
                tmp.ReadPixels(new Rect(0, 0, w, h), 0, 0);
                tmp.Apply(false);
                return tmp.GetPixels32();
            }
            finally
            {
                RenderTexture.active = prev;
                RenderTexture.ReleaseTemporary(rt);
                if (tmp != null) Object.DestroyImmediate(tmp);
            }
        }

        static void WritePng(Color32[] px, int w, int h, string assetPath)
        {
            var tex = new Texture2D(w, h, TextureFormat.RGBA32, false);
            try
            {
                tex.SetPixels32(px);
                tex.Apply(false);
                string full = Path.Combine(Directory.GetCurrentDirectory(), assetPath);
                File.WriteAllBytes(full, tex.EncodeToPNG());
            }
            finally { Object.DestroyImmediate(tex); }
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceSynchronousImport);
        }

        static bool GenerateMask(TexGroup g, string outPath)
        {
            Texture2D rough = Load(g.rough), metal = Load(g.metal), ao = Load(g.ao), arm = Load(g.arm);
            Texture2D size = rough ?? arm;
            if (size == null) return false;
            int w = Mathf.Min(size.width, 2048), h = Mathf.Min(size.height, 2048);
            Color32[] armPx = arm != null ? ReadPixels(arm, w, h, false) : null;
            Color32[] roughPx = arm == null && rough != null ? ReadPixels(rough, w, h, false) : null;
            Color32[] metalPx = arm == null && metal != null ? ReadPixels(metal, w, h, false) : null;
            Color32[] aoPx = arm == null && ao != null ? ReadPixels(ao, w, h, false) : null;
            if (armPx == null && roughPx == null) return false;

            var outPx = new Color32[w * h];
            for (int i = 0; i < outPx.Length; i++)
            {
                byte metalV = armPx != null ? armPx[i].b : metalPx != null ? metalPx[i].r : (byte)0;
                byte aoV = armPx != null ? armPx[i].r : aoPx != null ? aoPx[i].r : (byte)255;
                byte roughV = armPx != null ? armPx[i].g : roughPx[i].r;
                outPx[i] = new Color32(metalV, aoV, 0, (byte)(255 - roughV));
            }
            WritePng(outPx, w, h, outPath);
            return true;
        }

        static bool GenerateBaseColorA(string diffPath, string alphaPath, string outPath)
        {
            Texture2D diff = Load(diffPath), alpha = Load(alphaPath);
            if (diff == null || alpha == null) return false;
            int w = Mathf.Min(diff.width, 2048), h = Mathf.Min(diff.height, 2048);
            var rgb = ReadPixels(diff, w, h, true);
            var a = ReadPixels(alpha, w, h, false);
            for (int i = 0; i < rgb.Length; i++) rgb[i].a = a[i].r;
            WritePng(rgb, w, h, outPath);
            return true;
        }

        // ------------------------------------------------------------------ materials

        static int BuildModelMaterials(string model, string fbx, StringBuilder log)
        {
            string texDir = $"{ModelsFolder}/{model}/textures";
            var groups = CollectTextureGroups(texDir);
            foreach (var g in groups.Values) EnsureGeneratedTextures(g, log);

            if (AssetImporter.GetAtPath(fbx) is not ModelImporter importer) return 0;

            // FBX sub-material names: embedded materials (first import) + already remapped source names (subsequent runs)
            var names = AssetDatabase.LoadAllAssetsAtPath(fbx).OfType<Material>().Select(m => m.name).Distinct().ToList();
            foreach (var kv in importer.GetExternalObjectMap())
                if (kv.Key.type == typeof(Material) && !names.Contains(kv.Key.name)) names.Add(kv.Key.name);
            if (names.Count == 0)
            {
                var go = AssetDatabase.LoadAssetAtPath<GameObject>(fbx);
                if (go != null)
                    foreach (var r in go.GetComponentsInChildren<Renderer>(true))
                        foreach (var m in r.sharedMaterials)
                            if (m != null && !names.Contains(m.name)) names.Add(m.name);
            }
            if (names.Count == 0) names.Add(model);

            MeshUtil.EnsureFolder(ModelMaterialsFolder);
            int count = 0;
            bool remapChanged = false;
            var existingMap = importer.GetExternalObjectMap();
            foreach (string matName in names)
            {
                string prefix = MatchPrefix(matName, groups.Keys, model);
                TexGroup g = prefix != null ? groups[prefix] : null;
                string part = matName.Equals(model, StringComparison.OrdinalIgnoreCase) ? "main"
                            : matName.StartsWith(model + "_", StringComparison.OrdinalIgnoreCase) ? matName.Substring(model.Length + 1)
                            : matName;
                foreach (char c in Path.GetInvalidFileNameChars()) part = part.Replace(c, '_');
                string path = $"{ModelMaterialsFolder}/{model}_{part}.mat";

                var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
                if (mat == null)
                {
                    mat = new Material(Shader.Find("HDRP/Lit")) { name = $"{model}_{part}" };
                    AssetDatabase.CreateAsset(mat, path);
                }
                ConfigureModelMaterial(mat, matName, g, model);
                var ident = new AssetImporter.SourceAssetIdentifier(typeof(Material), matName);
                if (!existingMap.TryGetValue(ident, out var already) || already != mat)
                {
                    importer.AddRemap(ident, mat);
                    remapChanged = true;
                }
                log.AppendLine($"  {model}: material '{matName}' -> {path} (textures: {(g != null ? g.prefix : "none")})");
                count++;
            }
            // re-importing a multi-million-triangle tree costs minutes and gigabytes (it crashed an 8 GB machine), so only do it when a remap actually changed
            if (remapChanged) importer.SaveAndReimport();
            else log.AppendLine($"  {model}: remaps unchanged, no reimport");
            return count;
        }

        /// <summary>Case-insensitive match of an FBX material name to a texture prefix: exact, else longest substring either way,
        /// else the prefix equal to the model name, else the first prefix.</summary>
        static string MatchPrefix(string matName, IEnumerable<string> prefixes, string model)
        {
            string n = matName.ToLowerInvariant();
            string best = null; int bestLen = -1;
            foreach (string p in prefixes)
            {
                string pl = p.ToLowerInvariant();
                if (pl == n) return p;
                if ((n.Contains(pl) || pl.Contains(n)) && pl.Length > bestLen) { best = p; bestLen = pl.Length; }
            }
            if (best != null) return best;
            foreach (string p in prefixes) if (p.Equals(model, StringComparison.OrdinalIgnoreCase)) return p;
            return prefixes.FirstOrDefault();
        }

        static void ConfigureModelMaterial(Material m, string matName, TexGroup g, string model)
        {
            string lower = matName.ToLowerInvariant();
            Texture2D baseTex = g != null ? (Load(g.baseA) ?? Load(g.diff)) : null;
            Texture2D normal = g != null ? Load(g.nor) : null;
            Texture2D mask = g != null ? Load(g.mask) : null;
            bool hasAlpha = g != null && g.baseA != null && baseTex != null && baseTex == Load(g.baseA);

            m.SetColor("_BaseColor", Color.white);
            m.SetTexture("_BaseColorMap", baseTex);
            m.SetTexture("_NormalMap", normal);
            m.SetFloat("_NormalScale", 1f);
            m.SetTexture("_MaskMap", mask);
            if (mask != null)
            {
                m.SetFloat("_Metallic", 1f); m.SetFloat("_Smoothness", 1f);
                m.SetFloat("_SmoothnessRemapMin", 0f); m.SetFloat("_SmoothnessRemapMax", 1f);
                m.SetFloat("_AORemapMin", 0f); m.SetFloat("_AORemapMax", 1f);
            }
            else
            {
                bool metallic = lower.Contains("metal") || lower.Contains("lamp") || lower.Contains("hydrant") || lower.Contains("manhole") || lower.Contains("statue");
                m.SetFloat("_Metallic", metallic ? 0.85f : 0f);
                m.SetFloat("_Smoothness", metallic ? 0.55f : lower.Contains("leaves") || lower.Contains("twigs") ? 0.25f : 0.35f);
            }

            if (hasAlpha)
            {
                HDMaterial.SetAlphaClipping(m, true);
                HDMaterial.SetAlphaCutoff(m, 0.5f);
                m.SetFloat("_DoubleSidedEnable", 1f);
                m.SetFloat("_DoubleSidedNormalMode", 1f); // mirror
            }
            else
            {
                HDMaterial.SetAlphaClipping(m, false);
                m.SetFloat("_DoubleSidedEnable", 0f);
            }

            if (lower.Contains("glass"))
            {
                HDMaterial.SetSurfaceType(m, true);
                m.SetFloat("_BlendMode", 0f);
                m.SetFloat("_EnableBlendModePreserveSpecularLighting", 1f);
                m.SetColor("_BaseColor", new Color(0.85f, 0.9f, 0.95f, 0.3f));
                m.SetTexture("_MaskMap", null);
                m.SetFloat("_Metallic", 0f); m.SetFloat("_Smoothness", 0.95f);
                m.renderQueue = (int)RenderQueue.Transparent;
            }
            else if (lower.Contains("bulb"))
            {
                var e = new Color(1f, 0.85f, 0.6f);
                m.SetFloat("_UseEmissiveIntensity", 1f);
                m.SetColor("_EmissiveColorLDR", e);
                m.SetFloat("_EmissiveIntensity", 800f);
                m.SetColor("_EmissiveColor", e * 800f);
                m.SetFloat("_EmissiveExposureWeight", 0.7f);
            }

            HDMaterial.ValidateMaterial(m);
            EditorUtility.SetDirty(m);
        }

        // ------------------------------------------------------------------ prefabs

        static bool BuildPrefab(string key, string model, string fbx, StringBuilder log)
        {
            var modelAsset = AssetDatabase.LoadAssetAtPath<GameObject>(fbx);
            if (modelAsset == null) return false;
            if (!Targets.TryGetValue(key, out var target)) target = new Target { size = 0f };

            MeshUtil.EnsureFolder(PrefabLibrary.Folder);
            string prefabPath = $"{PrefabLibrary.Folder}/{key}.prefab";

            var root = new GameObject(key);
            try
            {
                var inst = (GameObject)PrefabUtility.InstantiatePrefab(modelAsset);
                inst.name = model;
                inst.transform.SetParent(root.transform, false);
                // keep the importer's root rotation/scale (FBX axis fix-up + unit scale); only the position is normalised
                inst.transform.localPosition = Vector3.zero;
                var importRot = inst.transform.localRotation; var importScale = inst.transform.localScale;

                SelectVariant(inst, key, target, log);

                var renderers = inst.GetComponentsInChildren<Renderer>(false);
                foreach (var r in renderers)
                {
                    r.shadowCastingMode = ShadowCastingMode.On;
                    r.receiveShadows = true;
                    r.motionVectorGenerationMode = MotionVectorGenerationMode.Camera;
                }

                Bounds b = ComputeBounds(renderers, out bool ok);
                if (ok)
                {
                    float measure = target.horizontal ? Mathf.Max(b.size.x, b.size.z) : b.size.y;
                    if (measure > 1e-4f && target.size > 0f)
                    {
                        float ratio = target.size / measure;
                        if (ratio > ScaleTolerance || ratio < 1f / ScaleTolerance)
                        {
                            inst.transform.localScale = importScale * ratio;
                            log.AppendLine($"  {key}: measured {measure:F2} m, target {target.size:F2} m -> scale x{ratio:F3}");
                            b = ComputeBounds(renderers, out ok);
                        }
                    }
                    // pivot at ground level, centred in XZ
                    inst.transform.localPosition = new Vector3(-b.center.x, -b.min.y, -b.center.z);
                    b = ComputeBounds(renderers, out ok);
                }

                foreach (var t in root.GetComponentsInChildren<Transform>(true))
                    GameObjectUtility.SetStaticEditorFlags(t.gameObject, PropStaticFlags);

                long tris = CountTriangles(renderers);
                bool meshLod = HasMeshLod(renderers);
                if (tris > LodGroupTriangleThreshold && !meshLod)
                {
                    var lg = root.AddComponent<LODGroup>();
                    lg.fadeMode = LODFadeMode.None;
                    lg.SetLODs(new[] { new LOD(LodCullScreenHeight, renderers) });
                    lg.RecalculateBounds();
                }

                if (key.StartsWith("lamp", StringComparison.OrdinalIgnoreCase))
                {
                    var anchor = new GameObject("LampHeadAnchor");
                    anchor.transform.SetParent(root.transform, false);
                    anchor.transform.position = FindLampHead(renderers, b);
                }

                var saved = PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
                log.AppendLine($"  prefab {prefabPath}: size {b.size.x:F2}x{b.size.y:F2}x{b.size.z:F2} m, {tris} tris, meshLod={meshLod}, renderers={renderers.Length}");
                return saved != null;
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        /// <summary>Poly Haven packs several variants side by side in one FBX (shrub a-d, fresh/aged hydrant, two trash cans, a seating kit).
        /// Keep one variant: explicit child list when configured, else cluster every child around the "major" objects and keep the
        /// preferred / largest cluster. Overlapping majors (car body + wheels, manhole frame + cover) are treated as one assembly.</summary>
        static void SelectVariant(GameObject inst, string key, Target target, StringBuilder log)
        {
            var children = new List<Transform>();
            foreach (Transform c in inst.transform)
                if (c.GetComponentInChildren<Renderer>(true) != null) children.Add(c);
            if (children.Count < 2) return;

            if (target.keepChildren != null && target.keepChildren.Length > 0)
            {
                int kept = 0;
                foreach (var c in children)
                {
                    bool keep = target.keepChildren.Any(k => c.name.IndexOf(k, StringComparison.OrdinalIgnoreCase) >= 0);
                    c.gameObject.SetActive(keep);
                    if (keep) kept++;
                }
                if (kept == 0) foreach (var c in children) c.gameObject.SetActive(true);
                log.AppendLine($"  {key}: kept {kept}/{children.Count} children by name");
                return;
            }

            var infos = children.Select(c => (t: c, b: ComputeBounds(c.GetComponentsInChildren<Renderer>(true), out _))).ToList();
            float maxVol = infos.Max(i => Volume(i.b));
            if (maxVol <= 0f) return;
            var majors = infos.Where(i => Volume(i.b) >= 0.3f * maxVol).ToList();
            if (majors.Count < 2) return;
            var largest = majors.OrderByDescending(i => Volume(i.b)).First();
            if (!majors.Any(mj => mj.t != largest.t && !OverlapsXZ(mj.b, largest.b, 0.02f))) return; // one assembly

            var clusters = majors.ToDictionary(mj => mj.t, mj => new List<(Transform t, Bounds b)> { (mj.t, mj.b) });
            foreach (var i in infos)
            {
                if (clusters.ContainsKey(i.t)) continue;
                var nearest = majors.OrderBy(mj => DistXZ(mj.b.center, i.b.center)).First();
                clusters[nearest.t].Add(i);
            }

            Transform chosen = null;
            if (!string.IsNullOrEmpty(target.preferChild))
                chosen = clusters.Keys.FirstOrDefault(k => clusters[k].Any(e => e.t.name.IndexOf(target.preferChild, StringComparison.OrdinalIgnoreCase) >= 0));
            chosen ??= clusters.OrderByDescending(kv => kv.Value.Sum(e => Volume(e.b))).First().Key;

            int disabled = 0;
            foreach (var kv in clusters)
            {
                if (kv.Key == chosen) continue;
                foreach (var e in kv.Value) { e.t.gameObject.SetActive(false); disabled++; }
            }
            log.AppendLine($"  {key}: {clusters.Count} packed variants, kept cluster '{chosen.name}', disabled {disabled} object(s)");
        }

        static float Volume(Bounds b) => Mathf.Max(b.size.x, 1e-3f) * Mathf.Max(b.size.y, 1e-3f) * Mathf.Max(b.size.z, 1e-3f);
        static float DistXZ(Vector3 a, Vector3 b) => Vector2.Distance(new Vector2(a.x, a.z), new Vector2(b.x, b.z));
        static bool OverlapsXZ(Bounds a, Bounds b, float pad) =>
            a.min.x - pad <= b.max.x && b.min.x - pad <= a.max.x && a.min.z - pad <= b.max.z && b.min.z - pad <= a.max.z;

        static Mesh MeshOf(Renderer r)
        {
            if (r is SkinnedMeshRenderer smr) return smr.sharedMesh;
            var mf = r.GetComponent<MeshFilter>();
            return mf != null ? mf.sharedMesh : null;
        }

        /// <summary>World-space bounds from mesh bounds x renderer matrices (independent of renderer activity/culling state).</summary>
        static Bounds ComputeBounds(IEnumerable<Renderer> renderers, out bool ok)
        {
            ok = false;
            var b = new Bounds();
            foreach (var r in renderers)
            {
                var mesh = MeshOf(r);
                if (mesh == null) continue;
                var lb = mesh.bounds;
                var m = r.transform.localToWorldMatrix;
                for (int i = 0; i < 8; i++)
                {
                    var corner = new Vector3((i & 1) == 0 ? lb.min.x : lb.max.x, (i & 2) == 0 ? lb.min.y : lb.max.y, (i & 4) == 0 ? lb.min.z : lb.max.z);
                    var p = m.MultiplyPoint3x4(corner);
                    if (!ok) { b = new Bounds(p, Vector3.zero); ok = true; }
                    else b.Encapsulate(p);
                }
            }
            return b;
        }

        static long CountTriangles(IEnumerable<Renderer> renderers)
        {
            long n = 0;
            foreach (var r in renderers)
            {
                var mesh = MeshOf(r);
                if (mesh == null) continue;
                for (int s = 0; s < mesh.subMeshCount; s++) n += mesh.GetIndexCount(s) / 3;
            }
            return n;
        }

        static bool HasMeshLod(IEnumerable<Renderer> renderers)
        {
#if UNITY_6000_2_OR_NEWER
            foreach (var r in renderers)
            {
                var mesh = MeshOf(r);
                if (mesh != null && mesh.lodCount > 1) return true;
            }
#endif
            return false;
        }

        /// <summary>Centroid of the vertices in the top 12% of the lamp; falls back to the top centre of the bounds.</summary>
        static Vector3 FindLampHead(IEnumerable<Renderer> renderers, Bounds b)
        {
            try
            {
                float yMin = b.max.y - 0.12f * b.size.y;
                Vector3 sum = Vector3.zero; int n = 0;
                foreach (var r in renderers)
                {
                    var mesh = MeshOf(r);
                    if (mesh == null || (!mesh.isReadable && Application.isPlaying)) continue;
                    var m = r.transform.localToWorldMatrix;
                    foreach (var v in mesh.vertices)
                    {
                        var p = m.MultiplyPoint3x4(v);
                        if (p.y >= yMin) { sum += p; n++; }
                    }
                }
                if (n > 0) return sum / n;
            }
            catch (Exception) { /* non-readable mesh: fall back */ }
            return new Vector3(b.center.x, b.max.y, b.center.z);
        }

        // ------------------------------------------------------------------ data

        static void CopyCityJson(StringBuilder log)
        {
            string dst = CityData.DefaultPath;
            string full = Path.Combine(Directory.GetCurrentDirectory(), dst);
            if (File.Exists(full)) { log.AppendLine($"[AssetImportSetup] {dst} present"); return; }
            if (!File.Exists(CityJsonSource)) { Debug.LogWarning($"[AssetImportSetup] city.json source missing: {CityJsonSource}"); return; }
            MeshUtil.EnsureFolder(DataFolder);
            File.Copy(CityJsonSource, full);
            AssetDatabase.ImportAsset(dst);
            log.AppendLine($"[AssetImportSetup] copied city.json -> {dst}");
        }
    }
}
